# Generate a secondary branch that will hold the built user snake
# animation. The branch is then used via RAW access to serve the
# svg directly in the README file.
name: Generate snake animation

on:
  # Update on commit
  push:
    branches:
      - main
  # Refresh each sunday
  schedule:
    - cron: "0 0 * * 0"
  # Allow for manual refresh
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}